# Generated by Django 3.1.3 on 2020-11-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название гранта')),
                ('amount', models.IntegerField(verbose_name='Сумма гранта')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='ФИО организатора')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='ФИО волонтера')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название мероприятия')),
                ('rate', models.CharField(blank=True, choices=[('a', 'Наивысший'), ('б', 'Высокий'), ('в', 'Средний'), ('г', 'Низкий'), ('д', 'Наинизший')], default='в', max_length=1, verbose_name='Рейтинг мероприятия')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud.grant', verbose_name='Грант')),
                ('organizers', models.ManyToManyField(to='stud.Organizer', verbose_name='Организаторы')),
            ],
        ),
    ]
