# Generated by Django 3.1.3 on 2020-11-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_auto_20201119_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud.grant', verbose_name='Грант'),
        ),
    ]
