# Generated by Django 3.1.3 on 2020-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0004_auto_20201119_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО организатора')),
                ('score_count', models.IntegerField(verbose_name='Количество очков организатора')),
            ],
        ),
    ]
