# Generated by Django 3.1.3 on 2020-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0005_organizerrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizerRate',
        ),
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.CharField(choices=[('а', 'Наивысший'), ('б', 'Высокий'), ('в', 'Средний'), ('г', 'Низкий'), ('д', 'Наинизший')], default='в', max_length=1, verbose_name='Рейтинг мероприятия'),
        ),
        migrations.CreateModel(
            name='OrganizerRate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stud.organizer',),
        ),
    ]
