# Generated by Django 3.1.3 on 2020-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0006_auto_20201119_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(to='stud.Volunteer', verbose_name='Волонтеры'),
        ),
    ]
